apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  labels:
    app: demo-app
  name: demo-app
  namespace: acm-demo
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  selector:
    matchLabels:
      app: demo-app
