apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: demo-app
  namespace: demo-app
  labels:
    app: demo-app
  annotations:
    apps.open-cluster-management.io/github-path: demo-app
    apps.open-cluster-management.io/github-branch: main
spec:
  channel: demo-app/demo-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: localcluster
